"""Initial collector schema

Revision ID: 78b5d80d3bd9
Revises: 
Create Date: 2026-01-11 09:11:01.742171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78b5d80d3bd9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domain', sa.Enum('HOUSING', 'SPORTS', name='domaintype'), nullable=False),
    sa.Column('content_type', sa.Enum('ARTICLE', 'VIDEO', name='contenttype'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=1000), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('metadata_', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url'),
    schema='collector'
    )
    op.create_index(op.f('ix_collector_contents_domain'), 'contents', ['domain'], unique=False, schema='collector')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_collector_contents_domain'), table_name='contents', schema='collector')
    op.drop_table('contents', schema='collector')
    # ### end Alembic commands ###
